cms:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix:   /admin

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /api

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

#api
api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



#web:
#    resource: "@MyAppsWebBundle/Resources/config/routing.yml"
#    prefix:   /
#
#admin:
#    resource: "@MyAppsAdminBundle/Resources/config/routing.yml"
#    prefix:   /admin

#api:
#    resource: "@MyAppsApiBundle/Resources/config/routing.yml"
#    prefix:   /api
#
#myapps_core:
#    resource: "@MyAppsCoreBundle/Resources/config/routing.yml"
#    prefix:   /myapps

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
