<?php

namespace pos\CoreBundle\Repository;

/**
 * RetailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerRepository extends \Doctrine\ORM\EntityRepository
{
}
