<?php

namespace MyApps\CoreBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    const ACCOUNT_TYPE_RETAILER = 'retailer';

    public function _parseRetailerUserProfiles($user, $retailer) {
        return array(
            'id' => $user->getId(),
//            'retailer_id' => $retailer ? $retailer->getId() : '',
            'user_id' => $user->getUsername(),
//            'shop_name' => $retailer ? $retailer->getName() : '',
//            'user_full_name' => $user->getFullName(),
//            'contact_name' => $retailer ? $retailer->getContactName() : '',
//            'contact_number' => $retailer ? $retailer->getContactPhone() : '',
//            'address' => $retailer ? $retailer->getAddress() : '',
//            'province' => $retailer ? $retailer->getAddressProvince() : '',
//            'city' => $retailer ? $retailer->getAddressCity() : '',
//            'country_code' => $retailer && $retailer->getCountry() ? $retailer->getCountry()->getCountryCode() : 'vn',
//            'dial_code' => $retailer && $retailer->getCountry() ? $retailer->getCountry()->getDialCode() : '+84',
//            'country_name' => $retailer && $retailer->getCountry() ? $retailer->getCountry()->getCountryName() : 'Vietnam',
//            'currency' => $retailer && $retailer->getCountry() ? $retailer->getCountry()->getCurrency() : 'VND',
//            'retailer_status' => $retailer ? $retailer->getStatus() : ''
        );
    }
}
