services:
#    my_apps_api.example:
#        class: MyApps\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    #this class override jwt_token_authenticator
    api.jwt_token_authenticator:
            class: MyApps\ApiBundle\Security\Guard\JWTTokenAuthenticator
            parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator



    # This class is used for checking API authorization in firewall of the security configuration
    api.token_authenticator:
        class: MyApps\ApiBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder', '@doctrine.orm.entity_manager']